language: node_js
node_js:
- '6'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: adamjmcgrath@gmail.com
  api_key:
    secure: UDX2+y2C7Qk+fSZjmnLtsI1HCjPvlbuFghoFhFwuLXwtgyxlihGVPgNG0k4klf9k64ACnjV1ZPSCZIDSFKGfy7DWOwMbQwVlHCy7bhbqZuopgnViekrZcX1zBphR0WguCFSC7xhqIQCMhgJiZ8hjrQV9btyd0mrmWxufSyFCkTg6JRxFXBZHD2CZ3HorI5jByUzOE96RZhf6C44xKGDLztXqZR186v3CDX12YL2kPng6F93nFRKslQ41Ev9DTGV5sFigPRZiIaRcIA6CLsHhBibjoU8qUJWCg4OIITPZJntnsZfrs7Kms5anhv4iF2nMkHEj/Vbs7JjPPvBdlVeW7kIyXUza8Sje8PtP3CT0hAZg4nkwprn/Kfd0xZNFfwgJuNVi1XCc6otqwo5AH90kA+P0UoH0qVY1O+wzHwW+whBnDP52X/UeyUFuCoW9t4ub5vP4IprSrdp8A6U9R+VK2lcJk7+CmWIFM4PjDIDkbUWrN3wpYNkSCNKe73kNfIl8WlBi9BuCmYcqqb/QLkWLn1dLXQk/A2vmGA+bvPmiFBYSFIrbjgn1LkYiKctz5dDwtncFIz3/Xdh9FcaROwzog+cbFHkCGEc5ZZNdzineTjwIvWXpIjGvn8ixrdLEhoVkFZuolx+EmU5prwasYY8EG8OFzUTRxqduO3g6gIx9/8E=
  on:
    tags: true
    repo: adamjmcgrath/oauth
  skip_cleanup: true
