language: node_js
node_js:
- '6'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: adamjmcgrath@gmail.com
  api_key:
    secure: "U1U7H5oECuVdaEZnjsFPw9OgF809iCeNETI8mZZ/bHfC0WYwrsFWDhvRlRcO8pyN+97Mf2iNbR4PL2xtUHbmG2STaXhbTaDL0Rx0YgpEepp1ZVUAtDbZST3if+1RmxXHZIXohAo9k1gATibVHQgUWUqCQCI8D2NvPDOqchFoCOLngaIYXmc/pja9pISF2gegjEmcdohogK5VP3CVgU3TQpSOIJfFBKP1ywi8IoR/KEUVF8LFgIvpimhstjUj34uq7sq9K1xBmPXY1S/9muiWB/rkGYy+nvXLWNRbiDGtLVm58BcLaqCTrRgmtCpghUkLMsLSoBswJvZOOSFQO6z12ZaqZWngaHgxzktSU2PcQ1lI/2YRi3zaY+cwymBNo3n6H9WJuNrI9OcfUdc7IyLL5q+X5FvS0MxIgqWdUHqcgRzC6VVr6tbgf6mLe3oNotvRPVYqyh6lkA4fOYK/iGxQlM5TiXOjGp1jaC3xQKNBN6uaI+IuK16XbPt4tEelsi+dReyvJpMH6XfZuhyijm2Di4CCbAnEuSgH8OjfsWOj+CaUkR87bGQKe7GxdSwUSRI0TLhMLCQwaFFdmVnLZynQ0OQtgEZDWkEfi/SArI79k3faWXrM4HBJEnFuSP/8XeOA9+za4PsnPmFicTGRWBnWoW8jjSZDtZFSX0nrKIw9/Hg="
  on:
    tags: true
    repo: adamjmcgrath/oauth
  skip_cleanup: true
