language: node_js

node_js:
- '6'

script:
  - npm test
  - npm run build

deploy:
  provider: npm
  email: adamjmcgrath@gmail.com
  api_key:
    secure: "kHRjXkg97hv8shD0kbTpnqZYgaUtghgPYo153vpRcbIjVsPTZgCvfKiuQ/zd7wMR3M4A1Jqt+C/HGAE8etoCQ0gq7CX96P1CIl/gxc35nKuHWzbefDUW4zbTPHBtNUiUr7TuaSflfTDXJAfiruJkAbts1OSV+lWS8xIUmBwepael6FdtRYkaKJ2aYzup/eBBASUYUBpQfDcokhvwO0sKgZuJ6Q+CIOH0dgnc5hiTv+xMPUaW8JmFW7mtqunkAymw4cg6yia5qzvV5Z6nRS+zypp1W5TyxwvElz4+Mp0IbFQ8fkjkL9oqC9xIgwTmjTEqMdVRt0e/ghmKJwfl8HdEmE2k6IhLu2SSaGjwmcAVhKAhG4vBGfNWsFOhPRDflgF9eGkCR4q4ltpbS5Zc7lwKTxgm3dAL6ul1MePe8RGPOCvjVjcCNPXz6IbUHYOrHlvcizAJtIo0aNiYMGpb0JtZ3if/DwZWoXv1oRQHCUd7AHnkFepP9/bVTaj0SHyF+rFli2nClg5DPFnYCAu7TwP+dkh7reG6n1a2i8DEWlPCCtLtv2q/uat7Vehkn6+4d3hgL0KkbDf5f0/fUOB7Me74N4URPWq3KXOnglGiZFJN9FxNgjJl499lx6JX/mFyS0rpokWLZC1+I4JF/u0WUP8PW1XQ+41yOBy5I4aT2mY0dsk="
  on:
    tags: true
    repo: adamjmcgrath/oauth-login
  skip_cleanup: true
